### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by feinstruktur**
I've added a `docker` command with three sub commands `init`, `run`, `enter` to the cli.

I deviated from how the `heroku` subcommand does things, see 2ef7879e97b1b79ba3be1e53b223194be0532984 for the rationale. It may make sense to change `heroku` accordingly.

Here's a brief video of what this looks like: https://vimeo.com/168056556

### CODE REVIEW

**Comment by feinstruktur** [comment]
One thing I just noticed: The way the original `Dockerfile` was set up (and I kept this) is to compile the app when building the image. I think it would be better to keep the image as is and run the compile as part of the run step, such that you only rarely need to run `init` and basically only use `run` in normal development.

**Comment by feinstruktur** [comment]
I just realised that I didn’t add my `Dockerfile` which is used in the `init` step. I’ll do that in the PR for now but the one people will likely use if from https://github.com/qutheory/vapor-example/blob/master/Dockerfile - after running `vapor new …`.

In oder not to spread this across two repos, it may be better to remove the `Dockerfile` in `vapor-example` and `curl` this one here when people run `docker init` for the first time.

**Comment by feinstruktur** [comment]
I’ve fixed the baking in of the local sources into the `Dockerfile` in fc81d9d31295778936af51155061d50509a6d32b. From the commit message:

Moved the `swift build` command from `RUN` to `CMD` and removed the `ADD` in the `Dockerfile`.

What these did was copy the sources and bake them as well as the build products (of the swift build) into the image when the image at image build time. That's bad, because it means any change in the sources would create a new image layer.

The better way is to map the local sources into the container at runtime (`docker run`) and run the `swift build` command as the container command, i.e. in `CMD`.

Hope that makes sense, let me know if you have questions.

**Comment by tannernelson** [comment]
This looks awesome. I added you to the Qutheory organization. Could you create a branch `qutheory/vapor-cli:docker` and merge everything from your `feinstruktur/vapor-cli:docker` into it?

This way I can test on my computer (never tried Docker before so it will be a good test) and fix some of the formatting.

**Comment by feinstruktur** [comment]
Thanks for the invite - I just tried to push:
```
ERROR: Permission to qutheory/vapor-cli.git denied to feinstruktur.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Do I have write access?

**Comment by tannernelson** [comment]
Should work now.

**Comment by feinstruktur** [comment]
Sweet, thanks! Branch is there now, let me know how it goes.

**Comment by feinstruktur** [comment]
PS: Since you haven’t tried to use docker before: If you don’t have the Mac Docket beta (it may still be invite only, not sure) you’ll have to be aware that the hosting doesn’t happen on `localhost` but via the `docker-machine` vm. The Mac Docker beta does away with that and makes it work similar to `docker` on Linux.

Once you have `docker` up and running, you’ll want to copy the `Dockerfile` here into the example dir and use it with the `vapor` script from this branch obviously :)

Hope that helps, docker can be a bit steep especially when you need to use `docker-machine` locally.

**Pull request closed without merging**
