### PR TITLE
Fix trim

### PR DESCRIPTION
**Pull request by feinstruktur**
Revert trim command to trim all whitespace by default (fixing `docker build`)

### CODE REVIEW

**Comment by tannernelson** [comment]
Uh oh this one got some conflicts :(

**Comment by feinstruktur** [comment]
Ive got 5mins let me look

**Comment by feinstruktur** [comment]
Merged cleanly but I didn’t have time to test!

**Comment by LoganWright** [comment]
This looks good to me! :shipit:

**Pull request merged**
