### PR TITLE
Spm

### LINKED ISSUE #24: Move script to SPM
The main source file is getting quite big so I’ve taken a quick look into what it could look like broken up into separate files and built it with SPM on both OSX and Linux (DEVELOPMENT-SNAPSHOT-2016-05-09-a) here: https://github.com/qutheory/vapor-cli/tree/spm

The pros are:

- Better code organisation. There was already at least one case where duplicate functionality was implemented because the authors presumably didn’t see the pre-existing one (`getCommand(id:)`)
- Testability beyond just running the top level commands in Travis
- Fastest version deployed, don’t need to rely on people discovering and running `self compile` (plus we can get rid of that hack)
- We can use 3rd party libs that support OSX and Linux (like perhaps [Swiftline](https://github.com/oarrabi/Swiftline)) rather than re-implement everything ourselves just so we can stuff it into one file. (I checked that source libs get compiled into the resulting binary so we don’t have to deal with external frameworks or libs.)

Cons:

- Deployment is more complicated as we’d have to
  - build two variants, OSX and Linux - ideally automatically from Travis
  - switch on architecture on download or provide different d/l urls

### PR DESCRIPTION
**Pull request by feinstruktur**
Fixes #24 

I just realised that I hadn't opened a PR for this yet :/ 

I've merged in latest changes from master just now. This will continue to be tricky and generate merge conflicts every time due to the way `vapor.swift` is no more in this branch.

It would be great if we could merge this next so we can avoid the tricky merges from master. The only thing that still needs changing is reviewing the install/update process in the spm context, i.e. by downloading the bootstrap script and running it instead of downloading the vapor script and compiling it. This should be simple and I'll look into that once soon as we're sure we're going down this path.

See #24 for more details.

### CODE REVIEW

**Comment by tannernelson** [comment]
Had to push out the last update, but I won't push anymore to master. Let's get this straightened out this week. :)

**Comment by feinstruktur** [comment]
Haha, in WWDC week? Let's see how that goes ;) I'll try and fix up the remaining bits tomorrow.

**Comment by feinstruktur** [comment]
@tannernelson just looking into merging 0.5.3 into this branch I noticed that there seems to have been an issue with installing that made you bring the `install` command back: 8f478531f5a6456cbc54ca4b0bd64d9b4372cd87. I’m going to drop this as part of the merge because this bit doesn’t really make sense with the `bootstrap.swift` script but it would be good to understand what the problem was so I don’t re-introduce it.

Have you got a problem description that I could test against? Thanks!

**Comment by feinstruktur** [comment]
@tannernelson I’m done with this but there are two things to do after merging.

1. The branch where `bootstrap.swift` pulls from is set to this branch, `spm`, right now, on order to make the tests pass. We’ll either need to change that or make it a parameter, defaulting to `master`. Just keeping the branch name in there is easier for now, otherwise we’d need to do more parameter parsing.

2. I’ve had to disable the `vapor update` test, because it cannot work until we’re serving `bootstrap.swift` from `cli.qutheory.io`. Actually, it may be better to change to a new URL, for example `vapor-cli.qutheory.io`, and switch over before merging. That way old clients won’t fall over.

**Comment by feinstruktur** [comment]
PS: Changes to be made are FIXME labeled

**Comment by tannernelson** [comment]
I'm going to merge this for now so we don't make any more accidental changes.

But I have a few things I want to add before we tag. Like support for Vapor's commands.

Nice work on this @feinstruktur!

**Comment by feinstruktur** [comment]
Thanks @tannernelson :) Not sure what exactly you mean by "Vapor's commands" but if you've got some specifics I can find some time this week to look into it. Now that this is in, I was also going to look into adding some unit tests via `swift test`.

**Comment by tannernelson** [comment]
Unit tests would be awesome. The Vapor commands can be read about in the docs here: https://vapor.readme.io/v0.12/docs/command

Basically Vapor has a little bit of CLI functionality itself now for serving and running preparations (migrations).

You run this by doing `.build/debug/App serve` `.build/debug/App prepare --revert` etc.

I want to make the CLI reduce the typing here by doing `vapor run serve`

To accomplish this we would need to parse the Package.swift to figure out the name of the package, then  run the executable from either the debug or release folders.

so something like `vapor run serve --release` would translate to `.build/release/MyAppName serve`

**Comment by tannernelson** [comment]
Also if you look at the console stuff powering that, you can see there's some cool code here for doing colors, etc.

I think it could be worth breaking this out into it's own package so both Vapor and the CLI can use it: https://github.com/qutheory/vapor/tree/master/Sources/Vapor/Console

**Comment by feinstruktur** [comment]
Cheers, I've created tickets #32, #33, and #34 for those

**Pull request merged**
