### PR TITLE
Tests

### LINKED ISSUE #32: Add unit tests
Now that `vapor-cli` is SPM based, we should add some proper unit tests.

### PR DESCRIPTION
**Pull request by feinstruktur**
Added unit tests - fixes #32 

This required a little restructuring to make it work with Linux, where there are two `main` functions otherwise.

Note that I added a test runner script and its logs output to the repo. See [this post](http://finestructure.co/blog/2016/6/20/serverless-continuous-integration) for some motivation. While it is somewhat redundant with Travis running tests I still find it useful to be able to run on both platforms locally while developing. I’d definitely keep the test runner but I could see people not wanting the `test.log` as well.

Test coverage cannot currently be enabled with a separate toolchain. This will be possible once https://github.com/apple/swift-package-manager/pull/184 has been merged and released (probably with 3.0-preview-2)

Speaking of test coverage - it’s going to be quite low for the moment, because large parts are hard to test as is. I’ll have a look if this can be improved by refactoring the code a little in a separate PR.

### CODE REVIEW

**Comment by tannernelson** [comment]
Yeah we should have test coverage in preview 2. Can you gitignore the xcode project?

**Comment by feinstruktur** [comment]
Hold on a sec before merging this, please. There’s another branch spm-2 which should go first.

**Comment by feinstruktur** [comment]
That’s up now as PR #37. This branch here is a continuation and I wouldn’t want to mix the business of updating the download URL with the tests.

**Comment by feinstruktur** [comment]
I’ve finished the first pass of adding tests to all the commands and will merge my branch `tests-2` into this one.

**Pull request merged**
